# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Feijiang Han"
description              : "Feijiang Han (韩非江) - NLP Researcher at UPenn | Research in Large Language Models (LLMs), Vision-Language Models (VLMs), WebShell Detection, Layout Analysis, and Crowdsensing | 自然语言处理 深度学习 机器学习"
repository               : "Feijianghan/Feijianghan.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      : G-XMDWG8RXJ1 # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification : dMgjss1TidDcPLVvrGR-J8k9sqRdKIkbgKYnfK3G_kU # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   : 840E1408A8FBA11C67FA0F1C303FC59F # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  : codeva-Vmc6w9FEF7 # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Feijiang Han"
  avatar           : "images/Chase-photo.jpg"
  bio              : "NLPer @ UPenn | Developing Efficient, Effective, and Explainable Methods for (M)LLMs | Aspiring PhD and Entrepreneur"
  location         : "Philadelphia, USA"
  employer         : "University of Pennsylvania"
  pubmed           : 
  googlescholar    : "https://scholar.google.com.hk/citations?user=PEJ5x3EAAAAJ"
  email            : "feijianghan@gmail.com"
  researchgate     :  # e.g., "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "Feijianghan"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "feijianghan"
  dblp             : # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : # e.g., "https://orcid.org/xxxx"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
  xiaohongshu     : "https://www.xiaohongshu.com/user/profile/5f96bb470000000001009db4"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
